// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYu1Ra0nw1ndxuYKg2EBHhWaoyJ8zybT4',
    appId: '1:1009375459994:web:91404599e45e8cc3c8fd23',
    messagingSenderId: '1009375459994',
    projectId: 'ecommerce-r90788',
    authDomain: 'ecommerce-r90788.firebaseapp.com',
    storageBucket: 'ecommerce-r90788.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fwPCzqxE470XnZ23BTvlu9Xoon_OXJg',
    appId: '1:1009375459994:android:0621e1a17885c9f0c8fd23',
    messagingSenderId: '1009375459994',
    projectId: 'ecommerce-r90788',
    storageBucket: 'ecommerce-r90788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHb_4DEqqpkG8TKlEx7Df7tSJtMcO772E',
    appId: '1:1009375459994:ios:3cdb42fbcedfdc44c8fd23',
    messagingSenderId: '1009375459994',
    projectId: 'ecommerce-r90788',
    storageBucket: 'ecommerce-r90788.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHb_4DEqqpkG8TKlEx7Df7tSJtMcO772E',
    appId: '1:1009375459994:ios:3cdb42fbcedfdc44c8fd23',
    messagingSenderId: '1009375459994',
    projectId: 'ecommerce-r90788',
    storageBucket: 'ecommerce-r90788.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYu1Ra0nw1ndxuYKg2EBHhWaoyJ8zybT4',
    appId: '1:1009375459994:web:a4fff0e0ffa97902c8fd23',
    messagingSenderId: '1009375459994',
    projectId: 'ecommerce-r90788',
    authDomain: 'ecommerce-r90788.firebaseapp.com',
    storageBucket: 'ecommerce-r90788.appspot.com',
  );
}
